/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import Entidades.Materia;
import java.util.Iterator;
import javax.swing.JOptionPane;

/**
 *
 * @author Brian D
 */
public class FormularioMaterias extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormularioMaterias
     */
    public FormularioMaterias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtCodigo = new javax.swing.JTextField();
        jtNombreMateria = new javax.swing.JTextField();
        jtAño = new javax.swing.JTextField();
        jbGuardar2 = new javax.swing.JButton();
        jbNuevo2 = new javax.swing.JButton();
        jbSalir2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setText("Codigo de materias");

        jLabel2.setText("Nombre de la materia");

        jLabel3.setText("Año al que pertenece");

        jtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCodigoActionPerformed(evt);
            }
        });

        jbGuardar2.setBackground(new java.awt.Color(102, 255, 204));
        jbGuardar2.setText("Guardar");
        jbGuardar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardar2ActionPerformed(evt);
            }
        });

        jbNuevo2.setBackground(new java.awt.Color(102, 255, 204));
        jbNuevo2.setText("Nuevo");
        jbNuevo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevo2ActionPerformed(evt);
            }
        });

        jbSalir2.setBackground(new java.awt.Color(102, 255, 204));
        jbSalir2.setText("Salir");
        jbSalir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalir2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial Black", 2, 18)); // NOI18N
        jLabel4.setText("Formulario de materias");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(140, 140, 140)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtCodigo)
                    .addComponent(jtNombreMateria)
                    .addComponent(jtAño, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jbGuardar2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jbNuevo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                        .addComponent(jbSalir2)
                        .addGap(114, 114, 114))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jtNombreMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbGuardar2)
                    .addComponent(jbNuevo2)
                    .addComponent(jbSalir2))
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtCodigoActionPerformed
            
    private void jbGuardar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardar2ActionPerformed
        if(jtAño.getText().isEmpty()||jtCodigo.getText().isEmpty()||jtNombreMateria.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "Debe ingresar datos..");
        }
                // AGREGO UN TRY EN CASO DE QUE EL USUARIO INGRESE CUALQUIER OTRA COSA MAKUMBERA MISITCA
             try{
           int codigoMateria = Integer.parseInt(jtCodigo.getText());
           int anioMateria = Integer.parseInt(jtAño.getText());
        if (!jtNombreMateria.getText().matches("[a-zA-Z ]+")){
        JOptionPane.showMessageDialog(null,"No se aceptan caracteres especiales..");
        jtNombreMateria.setText(" ");
        return; //para detener la ejecucion .. sirveeee
        }
        
 
           Iterator <Materia> it = GestorAlumnos.listaMateria.iterator();
           
           while(it.hasNext()){
            Materia ma = it.next();
            if(ma.getIdMateria()==codigoMateria){
            ma.setNombre(jtNombreMateria.getText());
            ma.setAnio(anioMateria);
            JOptionPane.showMessageDialog(null, "Datos actualizados..");
            break;
            }
            
           }
                }catch (NumberFormatException aux){
                 JOptionPane.showMessageDialog(null, "El codigo y el año deben ser numeros enteros..");
                 jtCodigo.setText(" ");
                 jtAño.setText(" ");
                }
             
   
    }//GEN-LAST:event_jbGuardar2ActionPerformed

    private void jbNuevo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevo2ActionPerformed
        if(jtAño.getText().isEmpty()||jtCodigo.getText().isEmpty()||jtNombreMateria.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "Debe ingresar datos..");
        }
        if (!jtNombreMateria.getText().matches("[a-zA-Z ]+")){
        JOptionPane.showMessageDialog(null,"No se aceptan caracteres especiales..");
        jtNombreMateria.setText(" ");
        }else{
        
        try{
            int numCodigo = Integer.parseInt(jtCodigo.getText());
            String nombreMateria = jtNombreMateria.getText();
            int numAnio = Integer.parseInt(jtAño.getText());
            Materia alumAux = new Materia(numCodigo,nombreMateria,numAnio);
            GestorAlumnos.listaMateria.add(alumAux);
            JOptionPane.showMessageDialog(null, "Se agrego correctamente la materia");
            jtCodigo.setText(" ");
            jtNombreMateria.setText(" ");
            jtAño.setText(" ");
        }catch(NumberFormatException vivaPeron){
        JOptionPane.showMessageDialog(null,"Datos incorrectos, vuelva a intentar");
                jtCodigo.setText(" ");
                jtNombreMateria.setText(" ");
                 jtAño.setText(" ");
            }
        }
    }//GEN-LAST:event_jbNuevo2ActionPerformed

    private void jbSalir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalir2ActionPerformed
         dispose(); 
    }//GEN-LAST:event_jbSalir2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbGuardar2;
    private javax.swing.JButton jbNuevo2;
    private javax.swing.JButton jbSalir2;
    private javax.swing.JTextField jtAño;
    private javax.swing.JTextField jtCodigo;
    private javax.swing.JTextField jtNombreMateria;
    // End of variables declaration//GEN-END:variables
}
